# Generated by Django 3.0.4 on 2020-03-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200322_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sem',
            field=models.CharField(blank=True, choices=[('S2', 'B Tech S2'), ('S4', 'B Tech S4'), ('S6', 'B Tech S6'), ('S8', 'B Tech S8'), ('M2', 'M Tech S2'), ('M4', 'M Tech S4')], max_length=3, null=True),
        ),
    ]
