# Generated by Django 3.0.4 on 2020-03-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_leadingquestion_cource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cource',
            new_name='course',
        ),
    ]
