# Generated by Django 3.0.4 on 2020-03-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200322_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadingquestion',
            old_name='cource',
            new_name='course',
        ),
    ]
