# Generated by Django 3.0.4 on 2020-03-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200322_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.IntegerField(),
        ),
    ]
