# Generated by Django 3.0.4 on 2020-03-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_user_next_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
    ]
