# Generated by Django 3.0.4 on 2020-03-22 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_question_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=120)),
                ('explanation', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Day')),
            ],
            options={
                'ordering': ('day__name', 'order_number', 'id'),
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='day',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='program',
            field=models.TextField(help_text='Write your program here.'),
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Lesson'),
        ),
    ]
