# Generated by Django 3.0.4 on 2020-03-22 19:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200323_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='next_task',
            new_name='next_lesson',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='question',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hint_viewed',
        ),
        migrations.AddField(
            model_name='lesson',
            name='completed',
            field=models.ManyToManyField(blank=True, to='dashboard.User'),
        ),
        migrations.AddField(
            model_name='question',
            name='hint_viewed',
            field=models.ManyToManyField(blank=True, to='dashboard.User'),
        ),
        migrations.AddField(
            model_name='reference',
            name='description',
            field=models.TextField(default='no description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadingquestion',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='explanation',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='logic',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='program',
            field=ckeditor.fields.RichTextField(help_text='Write your program here.'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='suggestions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
