# Generated by Django 3.0.4 on 2020-03-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200323_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('order_number', 'id')},
        ),
        migrations.AddField(
            model_name='leadingquestion',
            name='title',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order_number',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
