# Generated by Django 3.0.4 on 2020-03-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200323_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='next_lesson',
        ),
    ]
