# Generated by Django 3.0.4 on 2020-03-25 07:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20200325_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='question',
        ),
        migrations.AddField(
            model_name='faq',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=300, overwrite=True, populate_from=('title',), unique=True),
        ),
        migrations.CreateModel(
            name='WantedFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('user', models.ForeignKey(blank=TabError, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.User')),
            ],
        ),
    ]
