# Generated by Django 3.0.4 on 2020-03-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20200325_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='useful',
            new_name='clip_it',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='not_useful',
            new_name='needs_improvement',
        ),
    ]
