# Generated by Django 3.0.4 on 2020-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20200325_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='clip_it',
            field=models.ManyToManyField(blank=True, related_name='clipped_items', to='dashboard.User'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='needs_improvement',
            field=models.ManyToManyField(blank=True, related_name='voted_needs_improvement', to='dashboard.User'),
        ),
    ]
