# Generated by Django 3.0.4 on 2020-03-25 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20200325_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedfaq',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wantedfaq',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.User'),
        ),
    ]
