# Generated by Django 3.0.4 on 2020-03-25 12:42

import ckeditor.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20200325_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builtin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_keyword', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('code', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=('name',), unique=True)),
            ],
        ),
    ]
