# Generated by Django 3.0.4 on 2020-03-25 12:47

import ckeditor.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_builtin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(choices=[('keyword', 'KeyWord'), ('operator', 'Operator'), ('builtin_function', 'Builtin Functions')], default='keyword', max_length=30)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('code', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('supporting_versions', models.CharField(default='', max_length=120)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=('name',), unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Builtin',
        ),
    ]
