# Generated by Django 3.0.4 on 2020-03-26 05:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20200325_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course'),
        ),
        migrations.AddField(
            model_name='score',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course'),
        ),
        migrations.AddField(
            model_name='wantedfaq',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='code',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
