# Generated by Django 3.0.4 on 2020-03-26 05:57

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20200326_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=300, overwrite=True, populate_from=('title', 'pk')),
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=300, overwrite=True, populate_from=('name', 'pk')),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=('name', 'pk')),
        ),
    ]
